### PR TITLE
Add support for command group aliases

### PR DESCRIPTION
**Pull request by fbdtemme**
## Description

This adds support for aliases to command groups using the `AliasedOrderedGroup` class for click.
Update some internal keys to `single-cell-mpx` instead of `single-cell`

Fixes: EXE-1954

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Existing tests pass, pipeline passes, qc report is valid.

## PR checklist:

- [x] This comment contains a description of changes (with reason).
- [x] I have performed a self-review of my own code
- [] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If a new tool or package is included, I have updated poetry.lock, and [cited it properly](../CITATIONS.md)
- [ ] I have checked my code and documentation and corrected any misspellings
- [x] I have documented any significant changes to the code in [CHANGELOG.md](../CHANGELOG.md)

### CODE REVIEW

**Comment by fbdtemme** [comment]
There seems to be an issue with the updated version of tox and the use-current-env plugin.
This should be fixed in: #184

**Review by ambarrio — APPROVED** [review]
Great job!

**Comment by ambarrio** [comment]
One test crashing. Is the tox thing you found?

**Review by johandahlberg — COMMENTED** [review]
This looks good to me - I am a little bit concerned that some of the numeric the test results are changing. Do you have any feel for why that is?

**Comment by fbdtemme** [comment]
I have made a new test data generation run since to test the new meta.json files. 
These very small numerical changes are common whenever the testdata is rerun.
After the scope change of this ticket it is actually not needed to update the testdata so I'll drop that from the PR.

The test failures should indeed be fixed with the tox PR that is now merged.

**Pull request merged**
